### ISSUE TITLE
Menu gets buggy when maximizing

### ISSUE THREAD

**Issue by abeninskibede** [VPenkov/okayNav#13]
Hey the plugin looks great,
but there are some issues when maximizing the window and restore it back to original width and height.

http://screencast.com/t/WVg42FNO

**Comment by VPenkov** [comment]
This doesn't seem to occur in "normal" usage.
I'll investigate the issue.

**Comment by fergyfresh** [comment]
Maybe we don't have the proper header attributes? My nav is embedded in the header and I don't use the same flexbox stuff you use in the header and mine acts wonky.
https://github.com/fergyfresh/carpool/tree/okayNav

**Comment by VPenkov** [comment]
There might be issues when not using flexbox.
Should be taken care of in the next version. It seems that I was trying to do too much in a short timespan.

**Comment by fergyfresh** [comment]
@abeninskibede I will update this post if I have a workaround.

**Comment by VPenkov** [comment]
Fixed in the current version. Nav will now work with floats as well.

**Comment by curtiswilkinson** [comment]
Awesome plugin.
I've been attempting implement this to a testing navigation, and even after the recent commit for this issue I seem to be having the same problems as above. It still doesn't seem to be re-revealing menu options after they are hidden on window resizing for my implementation. 
![untitled screencast](https://cloud.githubusercontent.com/assets/12440573/13311764/ec1a6e0e-dbdc-11e5-9b71-acd925f98b21.gif)

**Comment by VPenkov** [comment]
Can I get a link to this?
Try wrapping the nav in a `<div id="nav-main-wrapper">` and initialize it like this:

``` javascript
$('#nav-main').okayNav({
    parent: '#nav-main-wrapper'
});
```

**Comment by curtiswilkinson** [comment]
I gave that a try with no luck, here is the link to the generic prototype of this: http://curtis.neto.com.au/

There has been some CSS changes obviously but the JS implemented is identical to the release for this issue.

Thanks for taking a look
